import React, {useState} from 'react';
import Popup from '../../../../UI/Popup/Popup';
import Button from '../../../../UI/Button/Button';
import {StructureColumnInterface} from '../../../../Library/Table/Interface/TableStructureInterface';
import {IndexKindType} from '../../../../Library/Table/Interface/StructureChangeInterface';

type IndexColumnType = {name: string, length: number | null};

interface IndexFormPropsInterface {
  columns: StructureColumnInterface[];
  hasPrimaryKey: boolean;
  busy: boolean;
  onPreview: (name: string, kind: IndexKindType, columns: IndexColumnType[]) => void;
  onCancel: () => void;
}

/** IndexForm - columns are added in order of clicking, prefix length is optional */
export default (props: IndexFormPropsInterface) => {
  const [name, setName] = useState<string>('');
  const [kind, setKind] = useState<IndexKindType>('INDEX');
  const [selected, setSelected] = useState<IndexColumnType[]>([]);

  const toggle = (columnName: string) => {
    setSelected((previous) => previous.some((column) => column.name === columnName)
      ? previous.filter((column) => column.name !== columnName)
      : [...previous, {name: columnName, length: null}]);
  };

  const setLength = (columnName: string, value: string) => {
    const length = parseInt(value, 10);
    setSelected((previous) => previous.map((column) => column.name === columnName
      ? {...column, length: Number.isFinite(length) && length > 0 ? length : null}
      : column));
  };

  const preview = () => props.onPreview(name.trim(), kind, selected);

  return (
    <Popup
      isOpen={true}
      label="Add index"
      onClickOk={preview}
      buttons={[
        <Button key="preview" size="small" colorVariant="success" label="Preview SQL" onClick={preview} loading={props.busy} disabled={!selected.length} />,
        <Button key="cancel" size="small" label="Cancel" onClick={props.onCancel} />,
      ]}
    >
      <div className="cmp-structure-form">
        <label>
          Kind
          <select value={kind} onChange={(e) => setKind(e.target.value as IndexKindType)}>
            <option value="INDEX">INDEX</option>
            <option value="UNIQUE">UNIQUE</option>
            <option value="FULLTEXT">FULLTEXT</option>
            <option value="PRIMARY" disabled={props.hasPrimaryKey}>PRIMARY KEY</option>
          </select>
        </label>
        {kind !== 'PRIMARY' && (
          <label>Name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="generated by database" /></label>
        )}
        <div className="index-columns">
          <div className="hint">Columns (in index order):</div>
          {props.columns.map((column) => {
            const position = selected.findIndex((item) => item.name === column.name);
            return (
              <div className="index-column" key={column.name}>
                <label className="checkbox">
                  <input type="checkbox" checked={position >= 0} onChange={() => toggle(column.name)} />
                  <span className="order">{position >= 0 ? position + 1 : ''}</span>
                  {column.name} <span className="hint">{column.type}</span>
                </label>
                {position >= 0 && (
                  <input
                    className="length"
                    type="number"
                    min={1}
                    placeholder="length"
                    value={selected[position].length ?? ''}
                    onChange={(e) => setLength(column.name, e.target.value)}
                  />
                )}
              </div>
            );
          })}
        </div>
      </div>
    </Popup>
  );
}
