
const ACTIONS = {
    LOGOUT: 'LOGOUT',
    DATABASE_LIST: 'DATABASE_LIST',
    SOCKET_DATABASE_LIST_APPEND_DATA: 'SOCKET_DATABASE_LIST_APPEND_DATA',
    SOCKET_GET_TABLES_FOR_DATABASE: 'SOCKET_GET_TABLES_FOR_DATABASE',
    SOCKET_SET_SELECT_QUERY_COLUMNS: 'SOCKET_SET_SELECT_QUERY_COLUMNS',
    SOCKET_SET_SELECT_QUERY_APPEND_DATA_ROW: 'SOCKET_SET_SELECT_QUERY_APPEND_DATA_ROW',
    SOCKET_SET_SELECT_QUERY_TOTAL_ROWS: 'SOCKET_SET_SELECT_QUERY_TOTAL_ROWS',
    SELECT_QUERY: 'SELECT_QUERY',
}

export { ACTIONS };
