DROP VIEW IF EXISTS struct_view;
DROP TABLE IF EXISTS struct_child, struct_test, edit_test, edit_nopk, value_test, csv_target CASCADE;
DROP TYPE IF EXISTS edit_status;
DROP FUNCTION IF EXISTS trg_struct_code_fn();
CREATE TYPE edit_status AS ENUM ('new', 'it''s done');
CREATE TABLE edit_test (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  status edit_status NOT NULL DEFAULT 'new',
  note TEXT NULL,
  created TIMESTAMP NOT NULL DEFAULT '2026-01-02 03:04:05',
  big BIGINT NULL,
  price NUMERIC(10,2) NULL
);
INSERT INTO edit_test (name, note, big, price) VALUES ('a', NULL, 9007199254740993, 1.10), ('b', 'x', NULL, NULL), ('c', 'y', NULL, NULL);
CREATE TABLE edit_nopk (a INT NULL, b VARCHAR(10) NULL);
INSERT INTO edit_nopk VALUES (1, 'x'), (1, 'x'), (NULL, 'n');
CREATE TABLE value_test (id SERIAL PRIMARY KEY, doc JSONB NULL, body TEXT NULL, data BYTEA NULL, flag BOOLEAN NULL, tags TEXT[] NULL);
INSERT INTO value_test (doc, body, data, flag, tags) VALUES
 ('{"name":"Anna","tags":["a","b"],"address":{"city":"Krakow","zip":"30-001"}}', repeat('Lorem ipsum dolor sit amet. ', 40), 'plain text in blob', true, ARRAY['x','y']),
 ('[1,2,3]', 'line 1' || chr(10) || 'line 2', decode(repeat('DEADBEEF', 600), 'hex'), false, NULL);
CREATE TABLE struct_test (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  customer_id INT NULL REFERENCES customers (id) ON DELETE SET NULL ON UPDATE CASCADE,
  status VARCHAR(1) NOT NULL DEFAULT 'a',
  title VARCHAR(200) NULL DEFAULT 'it''s untitled',
  created TIMESTAMP NOT NULL DEFAULT now(),
  total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_x2 NUMERIC(11,2) GENERATED ALWAYS AS (total * 2) STORED,
  CONSTRAINT uq_code UNIQUE (code)
);
COMMENT ON TABLE struct_test IS 'structure test';
COMMENT ON COLUMN struct_test.code IS 'business code';
CREATE INDEX idx_title_status ON struct_test (title, status);
CREATE TABLE struct_child (id INT PRIMARY KEY, struct_id INT NOT NULL, CONSTRAINT fk_child_struct FOREIGN KEY (struct_id) REFERENCES struct_test (id));
CREATE FUNCTION trg_struct_code_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.code := upper(NEW.code);
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_struct_code BEFORE INSERT ON struct_test FOR EACH ROW EXECUTE FUNCTION trg_struct_code_fn();
CREATE VIEW struct_view AS SELECT id, code FROM struct_test;
INSERT INTO struct_test (code, total, created) VALUES ('x1', 5, '2026-10-07 18:14:05'), ('x2', 7, '2026-10-07 18:14:05');
INSERT INTO struct_child VALUES (1, 1), (2, 2);
