
enum MessageType {
  DATABASE_BASE_ITEM = 'DATABASE_BASE_ITEM',
  TABLE_BASE_ITEM = 'TABLE_BASE_ITEM',
  SELECT_TOTAL_COUNT = 'SELECT_TOTAL_COUNT',
  SINGLE_SELECT_RECORD = 'SINGLE_SELECT_RECORD',
  SINGLE_SELECT_COLUMN = 'SINGLE_SELECT_COLUMN',
  QUERY_FINISHED = 'QUERY_FINISHED',
  QUERY_ERROR = 'QUERY_ERROR',
  ROW_CHANGES_PREVIEW = 'ROW_CHANGES_PREVIEW',
  ROW_CHANGES_APPLIED = 'ROW_CHANGES_APPLIED',
}

export default MessageType;
