
enum MessageType {
  DATABASE_BASE_ITEM = 'DATABASE_BASE_ITEM',
  TABLE_BASE_ITEM = 'TABLE_BASE_ITEM',
  SELECT_TOTAL_COUNT = 'SELECT_TOTAL_COUNT',
  SINGLE_SELECT_RECORD = 'SINGLE_SELECT_RECORD',
  SINGLE_SELECT_COLUMN = 'SINGLE_SELECT_COLUMN',
}

export default MessageType;
